version: '3.8'

services:
  TwitterMentions:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: TwitterMentions
    restart: unless-stopped
    environment:
      # Twitter API Configuration
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - TWITTER_TARGET_USERNAME=${TWITTER_TARGET_USERNAME}

      # Webhook Configuration
      - WEBHOOK_URL=${WEBHOOK_URL}

      # Application Configuration
      - NODE_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      - PORT=3000

      # Stream Configuration
      - STREAM_RECONNECT_ATTEMPTS=${STREAM_RECONNECT_ATTEMPTS:-10}
      - STREAM_RECONNECT_DELAY=${STREAM_RECONNECT_DELAY:-1000}
      - STREAM_KEEPALIVE_TIMEOUT=${STREAM_KEEPALIVE_TIMEOUT:-20000}

      # Webhook Configuration
      - WEBHOOK_TIMEOUT=${WEBHOOK_TIMEOUT:-10000}
      - WEBHOOK_RETRIES=${WEBHOOK_RETRIES:-3}
      - WEBHOOK_RETRY_DELAY=${WEBHOOK_RETRY_DELAY:-1000}

      # Health Check Configuration
      - HEALTH_CHECK_ENABLED=${HEALTH_CHECK_ENABLED:-true}

    ports:
      - "3000:3000"

    volumes:
      # Mount logs directory for persistent logging
      - ./logs:/app/logs

    networks:
      - TwitterMentions-network

    # Health check
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add a log viewer service for development
  logs-viewer:
    image: amir20/dozzle:latest
    container_name: TwitterMentions-logs
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - TwitterMentions-network
    profiles:
      - dev
    restart: unless-stopped

networks:
  TwitterMentions-network:
    driver: bridge

volumes:
  bot-logs:
    driver: local
